name: fortune_spin_wheel
description: A new Flutter project.
version: 0.0.2

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
